name: Move tags on new release

on:
  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  build:
    name: Build
    environment: dev_environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set dev tag
        run: |
          echo "Checking for an existing 'dev' tag"
          if git rev-parse -q --verify "refs/tags/dev" >/dev/null; then
            echo "Found an existing 'dev' tag"
            git tag -d dev
            git push origin --delete dev
          fi
          
          git tag dev
          git push origin dev

      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
