# -----------------------------------------------------------------------------------------------
# This workflow moves git tags to match with the latest releases and promotions (similar to ECR)
# AWS Pipelines can only check out source code by a predefined tag/commit/branch/hash
# -----------------------------------------------------------------------------------------------
# Enables our promotion pipelines to check out the correct release commit
#   in order to package and deploy the AWS CDK Lambdas
#   using a code snapshot of the released version to each environment.
# -----------------------------------------------------------------------------------------------

name: Move DEV Tag on Release

on:
  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{github.token}}

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set dev tag
        run: |
          echo "Checking for an existing 'dev' tag"
          if git rev-parse -q --verify "refs/tags/dev" >/dev/null; then
            echo "Found an existing 'dev' tag"
            git tag -d dev
            git push origin --delete dev
          fi
          
          git tag dev
          git push origin dev
        shell: bash

      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
