name: Move tags on new release

on:
  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{github.token}}

jobs:
  tag:
    name: Tag
    environment: dev_environment
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5
          token: ${{ github.token }}
      - name: Set dev tag
        run: |
          echo "Checking for an existing 'dev' tag"
          if git rev-parse -q --verify "refs/tags/dev" >/dev/null; then
            echo "Found an existing 'dev' tag"
            git tag -d dev
            git push origin --delete dev
          fi
          
          git tag dev
          git push origin dev

      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
