name: Release

on:
  push:
    branches:
      - uat

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install
        run: npm i
      - name: 'Cutting a Release'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
      - name: 'Update Main'
        run: |
          git config --global user.email "hello@curtisblanchette.com"
          git config --global user.name "curtisblanchette" |
          git checkout main |
          git merge uat |
          git push
