name: Trigger Release

on:
  workflow_dispatch:
    inputs:
      isDryRun:
        type: boolean
        description: Test the output of cutting a release without actually doing it.

env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
      - name: Install
        run: npm clean-install

      - name: 'Releasing (Dry Run)'
        if: ${{ github.event.inputs.isDryRun }}
        run: npx semantic-release --dry-run

      - name: 'Releasing'
        if: ${{ !github.event.inputs.isDryRun }}
        run: npx semantic-release