name: Release

on:
  push:
    branches:
      uat

env:
  GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: 'Cutting a Release'
        run: npx semantic-release