name: Trigger Release

on:
  workflow_dispatch:
    types: [semantic-release]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
      - name: Install
        run: npm clean-install
      - name: 'Cutting a Release'
        run: npx semantic-release

