name: Release

on:
  workflow_dispatch:
    inputs:
      isDryRun:
        type: boolean
        description: Dry Run

env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
      - name: Install
        run: npm clean-install

      - name: 'Releasing'

        run: |
          if [ "${{github.event.inputs.isDryRun}}" ] 
          then
            echo "=============================\n"
            echo "Releasing in DRY RUN mode\n"
            echo "=============================\n\n"
            npx semantic-release --dry-run
          else
            npx semantic-release
          fi
        shell: bash