name: Test
run-name: Release ${{github.event.inputs.isDryRun == 'true' && 'Dry Run' || ''}}

on:
  workflow_dispatch:
    inputs:
      source-tag:
        type: string
        description: source tag

env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Test
        id: test
        run: |
          echo "SOURCE_TAG=${{github.event.inputs.source-tag}}" >>${GITHUB_ENV}
          echo ${SOURCE_TAG,,}
          

